version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tgl
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - '3333:3333'
